#Location: /etc/mpv/

#sub-font='Arial Bold'
sub-font='Inter SemiBold'

sub-font-size=46
sub-border-size=1

# White
#sub-color=#FFFFFF'
# Yellow
#sub-color='#FFFF00'
# Light Gray
#sub-color='D3D3D3'
# Light Cyan
#sub-color='E0FFFF'
# Gold
sub-color='#FFD700'

sub-shadow=0
sub-shadow-color='#000000'
sub-shadow-offset=2

# Setting .ass subtitles
sub-ass-override=force

# Prefer English audio
alang=eng,en

# Prefer Spanish subtitles
slang=spa,es


